name: CD - Build & Push

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  IMAGE_NAME: fiap-fcg-user-api
  PROJECT_PATH: ./src/Fiap.FCG.User.WebApi/Fiap.FCG.User.WebApi.csproj
  STARTUP_PATH: ./src/Fiap.FCG.User.WebApi/Fiap.FCG.User.WebApi.csproj
  USER_CONNECTION_STRING: ${{ secrets.USER_CONNECTION_STRING }}
  JWT_KEY: ${{ secrets.JWT_KEY }}
  JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
  JWT_AUDIENCE: ${{ secrets.JWT_AUDIENCE }}

jobs:
  migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore & Build
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore
      - name: Instalar EF Core
        run: dotnet tool install --global dotnet-ef --version 8.*
      - name: Rodar migrations
        run: |
          "$HOME/.dotnet/tools/dotnet-ef" database update \
            --project src/Fiap.FCG.User.Infrastructure \
            --startup-project src/Fiap.FCG.User.WebApi

  build-and-push:
    runs-on: ubuntu-latest
    needs: migrations
    outputs:
      image_tag: ${{ steps.out.outputs.tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - uses: docker/setup-buildx-action@v3

      - name: Compute image tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,format=short,prefix=sha-

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          provenance: false

      - name: Expor tag gerada
        id: out
        run: |
          TAG="$(echo '${{ steps.meta.outputs.tags }}' | tail -n1 | awk -F: '{print $2}')"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    env:
      REGISTRY: ${{ secrets.REGISTRY }}
      APP:      ${{ secrets.AZURE_CONTAINERAPP }}
      RG:       ${{ secrets.AZURE_RG }}
      IMG_TAG:  ${{ needs.build-and-push.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true

      - name: Set subscription explicitly
        run: az account set --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"

      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ secrets.AKS_RG }}
          cluster-name: ${{ secrets.AKS_NAME }}

      - name: Apply manifest Kubernetes (User)
        run: |
          kubectl apply -f k8s-user.yaml

      - name: Atualizar imagem no Deployment (User)
        run: |
          kubectl set image deployment/fcg-user-api \
            fcg-user-api=${{ secrets.REGISTRY }}/fiap-fcg-user-api:${IMG_TAG} \
            -n fcg-user-ns

      - name: Aguardar rollout
        run: |
          kubectl rollout status deployment/fcg-user-api -n fcg-user-ns
